export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_FAILED = 'GET_POKEMONS_FAILED';
export const GET_POKEMONS_PENDING = 'GET_POKEMONS_PENDING';

export const SEARCH_POKEMONS = 'SEARCH_POKEMONS';
export const SEARCH_POKEMONS_SUCCESS = 'SEARCH_POKEMONS_SUCCESS';
export const SEARCH_POKEMONS_FAILED = 'SEARCH_POKEMONS_FAILED';
export const SEARCH_POKEMONS_PENDING = 'SEARCH_POKEMONS_PENDING';
